---
#- hosts: gateway
- hosts: all
  become: yes
  pre_tasks:

   - name: install unzip
     yum: name='unzip' state=latest

   - name: install gcc
     yum: name='gcc' state=present

   - name: install tar
     yum: name='tar' state=latest

   - name: install EPEL.
     yum: name='epel-release' state=present

    # yum: name='@^Development Tools' state=latest
#   nice to have but slow....
#  - name: performing base yum update.
#    yum: name='*' state=latest

  vars_files:
   - ../../vars/defaults.yml

 # tasks:
  roles:
   - openresty
   - restyother
   - apicast_dev
  # - java
  # - apicast_dev
